### ISSUE TITLE
User registration.

### ISSUE THREAD

**Issue by edtorba** [cwhite92/Plymouth-Entrepreneurs-Society#5]
Tried to register new user - showed me an SSL error message and that registration failed. However it still added it.

**Comment by edtorba** [comment]
Error message:
![Entrepreneurs Society Errors](https://f.cloud.github.com/assets/2422019/237458/725056ca-8814-11e2-953d-e83f83aaa253.png)

**Comment by JakeChampion** [comment]
I googled it quickly, just going climbing, will check more later.

http://stackoverflow.com/questions/1705856/socket-transport-ssl-in-php-not-enabled

**Comment by cwhite92** [comment]
This is down to your own individual PHP setups, you need to enable the SSL extension in `php.ini` I think.

The reason this happens is because it's using a Gmail account to send mail and the connect line is `ssl://smtp.gmail.com` (`app/Config/email.php`), PHP doesn't have a way of dealing with SSL in your configurations so it throws an error.

**Comment by cwhite92** [comment]
For users of XAMPP (Ed) open `xampp/php/php.ini` and uncomment the following line:

```
;extension=php_openssl.dll
```
